  # 配置数据源
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: cloud-eureka-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chou?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234

server:
  port: 80

eureka:
  instance:
    hostname: 127.0.0.1  #eureka服务实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eurka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-register: false
    service-url:
        #设置与eureka server交互的地址查询服务和注册服务都需要依赖的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
#         defaultZone: http://127.0.0.1:7001/eureka
  Server:
    #    关闭自我保护机制，保证不可用服务及时剔除
    enable-self-preservation: false




mybatis-plus:
  global-config:
    db-config:
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      updateStrategy: 1
